# See http://goreleaser.com for valid values
project_name: getmesh
builds:
  - binary: getmesh
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
